package com.example.nfc_support_lib.constant

const val SW_NO_ERROR = "9000"
const val SW_BYTES_REMAINING_00: String = "6100"
const val SW_WRONG_LENGTH: String = "6700"
const val SW_SECURITY_STATUS_NOT_SATISFIED = "6982"
const val SW_FILE_INVALID = "6983"
const val SW_DATA_INVALID = "6984"
const val SW_CONDITIONS_NOT_SATISFIED = "6985"
const val SW_COMMAND_NOT_ALLOWED = "6986"
const val SW_APPLET_SELECT_FAILED = "6999"
const val SW_WRONG_DATA = "6A80"
const val SW_FUNC_NOT_SUPPORTED = "6A81"
const val SW_FILE_NOT_FOUND = "6A82"
const val SW_RECORD_NOT_FOUND = "6A83"
const val SW_INCORRECT_P1P2 = "6A86"
const val SW_WRONG_P1P2 = "6B00"
const val SW_CORRECT_LENGTH_00 = "6C00"
const val SW_INS_NOT_SUPPORTED = "6D00"
const val SW_CLA_NOT_SUPPORTED = "6E00"
const val SW_UNKNOWN = "6F00"
const val SW_FILE_FULL = "6A84"


const val NFC_A_SUCCESS = "90"
const val NFC_A_SUCCESS_PRAMS = "91"
const val NFC_A_COMMON_ERROR = "10"
const val NFC_A_CMD_NOT_SUPPORT = "12"
const val NFC_A_PARAMS_WRONG = "13"
const val NFC_A_TAG_NO_RES = "50"
const val NFC_A_CMD_FAIL = "ee"